Update build-kernel.yml

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -16,6 +16,8 @@ jobs:
       run: |
         grep -v -E "^#|^\n" config.env | sed 's/ #.*//; s/#.*//' >> $GITHUB_ENV
 
+        cat $GITHUB_ENV
+
     - name: Remove unused packages
       if: env.REMOVE_UNUSED_PACKAGES == 'true'
       uses: jlumbroso/free-disk-space@main
@@ -164,17 +166,14 @@ jobs:
     - name: Setup KernelSU
       if: env.ENABLE_KERNELSU == 'true'
       run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
-        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s ${{ env.KERNELSU_TAG }}
-        if [ -d KernelSU ]; then
-            KSU_VERSION="_$(cd KernelSU && expr $(/usr/bin/git rev-list --count HEAD) + 10200)"
-        else
-            KSU_VERSION=""
-        fi
-        echo "UPLOADNAME=-KernelSU$KSU_VERSION" >> $GITHUB_ENV
-        if [ ${{ env.KSU_REVERT }} = true ]; then
-            git apply $GITHUB_WORKSPACE/patches/KSU_REVERT.patch
-        fi
+
+        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel 
+
+        
+        KSU_VERSION=$(cd KernelSU-Next && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
+
+
+        echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
 
     - name: Setup Configuration for Kernel
       run: |
@@ -260,8 +259,8 @@ jobs:
         export KBUILD_BUILD_HOST=Github-Action
         export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
         if [ -n ${{ env.KSU_EXPECTED_SIZE }} ] && [ -n ${{ env.KSU_EXPECTED_HASH }} ]; then
-          export KSU_EXPECTED_SIZE=${{ env.KSU_EXPECTED_SIZE }}
-          export KSU_EXPECTED_HASH=${{ env.KSU_EXPECTED_HASH }}
+          export EXPECTED_SIZE=${{ env.KSU_EXPECTED_SIZE }}
+          export EXPECTED_HASH=${{ env.KSU_EXPECTED_HASH }}
         fi
         make -j$(nproc --all) CC=clang O=out ARCH=${{ env.KERNEL_ARCH }} ${{ env.EXTRA_CMDS }} ${{ env.KERNEL_CONFIG }}
         if [ ${{ env.ENABLE_CCACHE }} = true ]; then
@@ -300,23 +299,7 @@ jobs:
       if: env.CHECK_FILE_IS_OK == 'true' && env.USE_CUSTOM_ANYKERNEL3 != 'true'
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
-
-
-
-        if [[ https://github.com/Jbub5/AnyKernel3 == *'.git' ]]; then
-           git clone https://github.com/Jbub5/AnyKernel3 -b proton --depth=1 AnyKernel3
-        else
-           wget -nv --tries=3 --timeout=30 -O AnyKernel3.zip https://github.com/Jbub5/AnyKernel3/archive/refs/heads/proton.zip
-           if [ $? -ne 0 ] || [ ! -s AnyKernel3.zip ]; then
-               echo "Failed to download AnyKernel3.zip or the file is empty!"
-               exit 1
-           fi
-           mkdir AnyKernel3
-           unzip AnyKernel3.zip -d AnyKernel3/
-        fi
-
-
-
+        git clone https://github.com/osm0sis/AnyKernel3 --depth=1 AnyKernel3
         sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
         sed -i 's!BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!BLOCK=auto;!g' AnyKernel3/anykernel.sh
         sed -i 's/IS_SLOT_DEVICE=0;/is_slot_device=auto;/g' AnyKernel3/anykernel.sh
@@ -326,31 +309,55 @@ jobs:
         fi
         rm -rf AnyKernel3/.git* AnyKernel3/README.md
 
+
+    
     - name: Make Custom-Anykernel3
       if: env.CHECK_FILE_IS_OK == 'true' && env.USE_CUSTOM_ANYKERNEL3 == 'true'
       run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        if [[ ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} == *'.tar.gz' ]]; then
-            wget -nv -O AnyKernel3.tar.gz ${{ env.CUSTOM_ANYKERNEL3_SOURCE }}
-            mkdir AnyKernel3
-            tar -C AnyKernel3/ -zxvf AnyKernel3.tar.gz
-        elif [[ ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} == *'.tar.xz' ]]; then
-            wget -nv -O AnyKernel3.tar.xz ${{ env.CUSTOM_ANYKERNEL3_SOURCE }}
-            mkdir AnyKernel3
-            tar -C AnyKernel3/ -Jxvf AnyKernel3.tar.xz
-        elif [[ ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} == *'.git' ]]; then
-            git clone ${{ env.CUSTOM_ANYKERNEL3_SOURCE }} -b ${{ env.CUSTOM_ANYKERNEL3_BRANCH }} --depth=1 AnyKernel3
-        else
-            wget -nv -O AnyKernel3.zip ${{ env.CUSTOM_ANYKERNEL3_SOURCE }}
-            mkdir AnyKernel3
-            unzip AnyKernel3.zip -d AnyKernel3/
-        fi
-        cp android-kernel/out/arch/${{ env.KERNEL_ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} AnyKernel3/
-        if [ ${{ env.CHECK_DTBO_IS_OK }} = true ]; then
-            cp android-kernel/out/arch/${{ env.KERNEL_ARCH }}/boot/dtbo.img AnyKernel3/
-        fi
-        rm -rf AnyKernel3/.git* AnyKernel3/README.md
+          cd $GITHUB_WORKSPACE/kernel_workspace
+          
+          echo "Starting to process AnyKernel3 source: https://github.com/Jbub5/AnyKernel3"
+          
+          # Download and extract the .zip source from the 'proton' branch
+          echo "Detected .zip source."
+          wget -nv --tries=3 --timeout=30 -O AnyKernel3.zip https://github.com/Jbub5/AnyKernel3/archive/refs/heads/proton.zip
+          if [ $? -ne 0 ] || [ ! -s AnyKernel3.zip ]; then
+              echo "Error: Failed to download or the file is empty (AnyKernel3.zip)!"
+              exit 1
+          fi
 
+          # Validate the downloaded file
+          unzip -t AnyKernel3.zip > /dev/null 2>&1
+          if [ $? -ne 0 ]; then
+              echo "Error: The downloaded AnyKernel3.zip file is invalid or corrupted!"
+              rm -f AnyKernel3.zip
+              exit 1
+          fi
+
+          # Create the directory and extract the content
+
+          unzip AnyKernel3.zip
+          mv AnyKernel3-proton/ AnyKernel3
+          if [ $? -ne 0 ]; then
+              echo "Error: Failed to extract AnyKernel3.zip!"
+              exit 1
+          fi
+
+          # Copy the kernel image to the AnyKernel3 directory
+          echo "Copying kernel image to AnyKernel3 directory."
+          cp android-kernel/out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
+
+          # Optional: Copy the dtbo.img if required
+          if [ "${NEED_DTBO}" = "true" ]; then
+              echo "Copying dtbo.img to AnyKernel3 directory."
+              cp android-kernel/out/arch/arm64/boot/dtbo.img AnyKernel3/
+          fi
+
+          # Clean up unnecessary files from AnyKernel3 directory
+          echo "Cleaning up unnecessary files from AnyKernel3 directory."
+          rm -rf AnyKernel3/.git* AnyKernel3/README.md
+
+          echo "Custom-Anykernel3 preparation completed successfully."
     - name: Make boot image
       if: env.HAVE_SOURCE_BOOT_IMAGE == 'true' && env.CHECK_FILE_IS_OK == 'true'
       run: |
@@ -371,6 +378,14 @@ jobs:
       with:
         name: AnyKernel3${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
         path: kernel_workspace/AnyKernel3/*
+
+
+    - name: Upload out
+      if: env.CHECK_FILE_IS_OK == 'true'
+      uses: actions/upload-artifact@v4
+      with:
+        name: OUT${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
+        path: $GITHUB_WORKSPACE/kernel_workspace/android-kernel/out/*
 
     - name: Upload ${{ env.KERNEL_IMAGE_NAME }}
       if: env.CHECK_FILE_IS_OK == 'true'
